# Generated by Django 5.0.7 on 2024-09-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('activity_level', models.CharField(max_length=50)),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('mediterranean', 'Mediterranean'), ('paleo', 'Paleo'), ('custom', 'Custom')], default='custom', max_length=15)),
                ('mental_state', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aifit.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('duration_minutes', models.IntegerField()),
                ('mood_before', models.CharField(max_length=100)),
                ('mood_after', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aifit.userprofile')),
            ],
        ),
    ]
